name: portscanner
services:
  main:
    stdin_open: true
    build: .
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/portscan/data:rw
